[workspace]
members = ["crates/dm-plugin-sdk", "examples/hello"]
default-members = ["."]
resolver = "3"

[package]
name = "dameng-cli"
version = "0.1.0"
edition = "2024"
description = "A minimal plugin host for Dameng database tools"
license = "MIT"
repository = "https://github.com/guangl/dameng-cli"
readme = "README.md"
keywords = ["dameng", "database", "cli", "plugins"]
categories = ["command-line-utilities", "database"]

[[bin]]
name = "dm"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
toml = "1.1.6"
dm-plugin-sdk = { version = "0.1.0", path = "crates/dm-plugin-sdk" }
