title: dameng-cli 插件开发文档
description: 使用、运维并通过 Rust 和 dm-plugin-sdk 开发 Dameng CLI 插件。
url: https://guangl.github.io
baseurl: /dameng-cli
lang: zh-CN
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - releasing.md
